Add Tooljet
meienberger/runtipi-appstore pull request #1088
Opened 2023-08-28 20:11 UTC by Jazys

Add Tooljet, a tool to build internal dashboard or CRM

2023-08-28 20:40 UTC, Jazys commented
update to pass test on CI/CD

2023-08-28 20:47 UTC, Jazys commented
update done

2023-08-29 19:23 UTC, meienberger requested changes

2023-08-29 19:23 UTC, meienberger commented on apps/tooljet/app.env
> +LOCKBOX_MASTER_KEY=70726290922441785304399601987729268981756953900892
These keys should be generated randomly ideally. There is a guide [here](https://www.runtipi.io/docs/contributing/adding-a-new-app#using-a-template-in-your-data-folder) in order to use template files. I can help you with an example if needed

2023-08-29 19:24 UTC, meienberger commented
Thanks for your PR!

2023-08-29 19:26 UTC, DrMxrcy requested changes

2023-08-29 19:26 UTC, DrMxrcy commented on apps/tooljet/docker-compose.yml
> +  client:
```suggestion
  tooljet-client:
```

2023-08-29 19:26 UTC, DrMxrcy commented on apps/tooljet/docker-compose.yml
> +  server:
```suggestion
  tooljet-server:
```

2023-08-29 19:26 UTC, DrMxrcy commented on apps/tooljet/docker-compose.yml
> +    container_name: postgres_tooljet
```suggestion
    container_name: db-tooljet
```

2023-08-29 19:26 UTC, DrMxrcy commented on apps/tooljet/docker-compose.yml
> +      - PG_HOST=postgres_tooljet
```suggestion
      - PG_HOST=db-tooljet
```

2023-08-29 19:26 UTC, DrMxrcy commented on apps/tooljet/docker-compose.yml
> +    environment:
Remove ENV File, Define Everything Here.

2023-08-29 19:26 UTC, DrMxrcy commented on apps/tooljet/config.json
> +  "id": "tooljet",
```suggestion
  "id": "tooljet-client:",
```

Must Match a container Name

2023-08-29 19:26 UTC, DrMxrcy commented on apps/tooljet/config.json
> +  "name": "tooljet",
```suggestion
  "name": "Tooljet",
```

2023-08-29 19:26 UTC, DrMxrcy commented on apps/tooljet/config.json
> +  "version": "2.14.0",
```suggestion
  "version": "v2.4.2",
```

2023-08-31 20:10 UTC, Jazys commented
Now all fix are made : 
- generate key from random function
- change service and container name

Is it possible to review changes ? @meienberger

2023-09-04 19:00 UTC, merged

2023-09-04 19:01 UTC, meienberger commented
Thanks!!