Add changedetection.io
meienberger/runtipi-appstore pull request #1277
Opened 2023-09-24 18:30 UTC by steveiliop56

2023-09-27 19:51 UTC, meienberger requested changes

2023-09-27 19:51 UTC, meienberger commented on apps/changedetection/metadata/logo.jpg
Can you center the icon? It looks weird in the app store

2023-10-01 13:38 UTC, steveiliop56 commented on apps/changedetection/metadata/logo.jpg
Umm its centered... Thats the icon from their repo. (sorry for late response)

2023-10-01 13:48 UTC, meienberger commented on apps/changedetection/metadata/logo.jpg
Where in the repo?

2023-10-01 16:44 UTC, steveiliop56 commented on apps/changedetection/metadata/logo.jpg
Cool

2023-10-01 16:59 UTC, meienberger approved these changes

2023-10-01 16:59 UTC, merged