Add Movary
meienberger/runtipi-appstore pull request #218
Opened 2023-03-12 07:23 UTC by DrMxrcy

(No Image so I used the Tipi Logo as a placeholder)

2023-03-20 21:59 UTC, meienberger commented
Can we also find a logo for this one?

2023-03-21 04:30 UTC, DrMxrcy commented
> Can we also find a logo for this one?

I did something similar to Tasks.md, found a close emoji and resized it.

2023-04-04 21:12 UTC, meienberger requested changes

2023-04-04 21:12 UTC, meienberger commented on apps/movary/metadata/logo.jpg
Can you also unzoom this icon?

2023-04-04 21:21 UTC, DrMxrcy commented on apps/movary/metadata/logo.jpg
Fixed in da9f708, Used a background as well.

2023-04-04 21:21 UTC, DrMxrcy commented on apps/movary/docker-compose.yml
> +    image: mysql:8.0
Fixed in da9f708

2023-04-05 06:00 UTC, meienberger requested changes

2023-04-05 19:01 UTC, meienberger approved these changes

2023-04-05 19:08 UTC, merged