Add Lidarr
meienberger/runtipi-appstore pull request #60
Opened 2022-10-07 00:13 UTC by andrewbrereton

2022-10-07 17:57 UTC, meienberger requested changes

2022-10-07 17:57 UTC, meienberger commented on apps/lidarr/docker-compose.yml
> +  sonarr:
change to lidarr

2022-10-07 17:57 UTC, meienberger commented on apps/lidarr/docker-compose.yml
> +      - tipi_main_network
Add the traefik labels to make it exposable 

```suggestion
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.lidarr.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.lidarr.entrypoints: websecure
      traefik.http.routers.lidarr.service: lidarr
      traefik.http.routers.lidarr.tls.certresolver: myresolver
      traefik.http.services.lidarr.loadbalancer.server.port: 8686
```

2022-10-07 17:57 UTC, meienberger commented on apps/lidarr/config.json
> +  "available": true,
```suggestion
  "available": true,
  "exposable": true,
```

2022-10-07 17:58 UTC, meienberger commented
Thank you very much for your pull request! I requested a few changes and we are ready to go

2022-10-07 21:22 UTC, andrewbrereton commented
Changes have been made. Requested a re-review.

2022-10-08 00:10 UTC, merged

2022-10-08 00:10 UTC, meienberger commented
Thank you 👍